baseURL = 'https://furukama.com/'
languageCode = 'en-us'
title = 'Furukama'
theme = 'bearcub'
enableGitInfo = true

[params]
  description = "Furukama"
  favicon = "/favicon.ico"
  
  [params.author]
    name = "Benedikt Koehler"
    email = "ben@furukama.com"
  
  # Social cards
  images = ["/images/social-card-default.png"]
  
  # Enable RSS
  [outputs]
    home = ["HTML", "RSS"]

# SEO optimizations
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[[menu.main]]
  name = "Blog"
  url = "/post/"
  weight = 1

[permalinks]
  post = "/:year/:month/:day/:title/"
  archives = "/:year/:month/:day/:title/"

# Social Media
[params.social]
  github = "furukama"
  bluesky = "furukama.bsky.social"
  linkedin = "benediktkoehler"
