baseURL = 'https://furukama.com/'
theme = 'bearcub'
enableGitInfo = true
canonifyURLs = true
enableRobotsTXT = true
timeout = "60s"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
disableKinds = []
timeZone = "Europe/Berlin"

[params]
  description = "Furukama"
  favicon = "/favicon.ico"
  generateSocialCard = true
  
  [params.author]
    name = "Benedikt Koehler"
    email = "ben@furukama.com"
  
  # Social cards
  images = ["/images/social-card-default.png"]
  
  # Enable RSS
  [outputs]
    home = ["HTML", "RSS"]

# SEO optimizations
[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "Notes"
  url = "/notes/"
  weight = 3

[[menu.main]]
  name = "Now"
  url = "/now/"
  weight = 4

[[menu.main]]
  name = "Reading"
  url = "/reading/"
  weight = 5

[permalinks]
  posts = "/:year/:month/:day/:title/"
  notes = "/:year/:month/:day/:title/"
  archives = "/:year/:month/:day/:title/"

# Social Media
[params.social]
  github = "furukama"
  bluesky = "furukama.bsky.social"
  linkedin = "benediktkoehler"
  twitter = "furukama"
