name: Test Tweet Workflow

on:
  workflow_dispatch:
    inputs:
      post_path:
        description: 'Path to blog post to tweet about'
        required: true
        default: 'content/blog/the-end-of-the-library.md'

jobs:
  test-tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Extract post metadata
        id: post_data
        run: |
          POST_PATH="${{ github.event.inputs.post_path }}"
          
          # Extract title and description
          TITLE=$(grep -m1 "^title:" "$POST_PATH" | sed 's/title: *"*\(.*\)"*/\1/')
          DESC=$(grep -m1 "^description:" "$POST_PATH" | sed 's/description: *"*\(.*\)"*/\1/')
          
          # Create URL
          FILENAME=$(basename "$POST_PATH" .md)
          URL="https://furukama.com/blog/$FILENAME/"
          
          # Compose tweet
          TWEET="📝 $TITLE\n\n$DESC\n\n$URL"
          
          # Ensure under 280 chars
          if [ ${#TWEET} -gt 280 ]; then
            AVAILABLE=$((280 - ${#URL} - 10))
            TEXT="📝 $TITLE - $DESC"
            TEXT="${TEXT:0:$AVAILABLE}..."
            TWEET="$TEXT\n\n$URL"
          fi
          
          # Output for next step
          echo "tweet<<EOF" >> $GITHUB_OUTPUT
          echo -e "$TWEET" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          
          echo "Tweet preview (${#TWEET} chars):"
          echo "========================================"
          echo -e "$TWEET"
          echo "========================================"
      
      - name: Send Tweet
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ steps.post_data.outputs.tweet }}
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}