name: Tweet New Posts

on:
  push:
    paths:
      - 'content/blog/*.md'
    branches:
      - main

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2
      
      - name: Check for new posts
        id: check
        run: |
          # Get added/modified blog posts
          NEW_POSTS=$(git diff --name-only HEAD~1 HEAD | grep '^content/blog/.*\.md$' | grep -v '_index.md' || true)
          echo "new_posts=$NEW_POSTS" >> $GITHUB_OUTPUT
          
          if [ -n "$NEW_POSTS" ]; then
            echo "Found new posts: $NEW_POSTS"
            
            # Process first post only (to avoid spam)
            FIRST_POST=$(echo "$NEW_POSTS" | head -n1)
            echo "first_post=$FIRST_POST" >> $GITHUB_OUTPUT
            
            # Extract metadata
            TITLE=$(grep -m1 "^title:" "$FIRST_POST" | sed 's/title: *"*\(.*\)"*/\1/')
            DESC=$(grep -m1 "^description:" "$FIRST_POST" | sed 's/description: *"*\(.*\)"*/\1/')
            
            # Create URL
            FILENAME=$(basename "$FIRST_POST" .md)
            URL="https://furukama.com/blog/$FILENAME/"
            
            # Compose tweet
            TWEET="📝 $TITLE\n\n$DESC\n\n$URL"
            
            # Ensure under 280 chars
            if [ ${#TWEET} -gt 280 ]; then
              AVAILABLE=$((280 - ${#URL} - 10))
              TEXT="📝 $TITLE - $DESC"
              TEXT="${TEXT:0:$AVAILABLE}..."
              TWEET="$TEXT\n\n$URL"
            fi
            
            echo "tweet<<EOF" >> $GITHUB_OUTPUT
            echo -e "$TWEET" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
          fi
      
      - name: Send Tweet
        if: steps.check.outputs.new_posts != ''
        uses: ethomson/send-tweet-action@v1
        with:
          status: ${{ steps.check.outputs.tweet }}
          consumer-key: ${{ secrets.TWITTER_API_KEY }}
          consumer-secret: ${{ secrets.TWITTER_API_SECRET }}
          access-token: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          access-token-secret: ${{ secrets.TWITTER_ACCESS_SECRET }}